### ISSUE TITLE
Display which team one is on

### ISSUE THREAD

**Issue by lamvdoan** [baritonehands/avalon#5]
Display color or something next to their name or so.  Minions of mordred/servant of aurther isn't straightforward for new players

**Comment by baritonehands** [comment]
![Screen Shot 2020-03-22 at 8 13 32 PM](https://user-images.githubusercontent.com/4118749/77270808-f9254280-6c7a-11ea-8480-376972564894.png)
![Screen Shot 2020-03-22 at 8 14 14 PM](https://user-images.githubusercontent.com/4118749/77270809-f9bdd900-6c7a-11ea-87d4-1376fa82265a.png)
![Screen Shot 2020-03-22 at 8 14 21 PM](https://user-images.githubusercontent.com/4118749/77270811-f9bdd900-6c7a-11ea-80a7-840e24c78301.png)
